package com.zc.model;

public class WxArticleField {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleField.id
     *
     * @mbg.generated Tue Jan 17 14:36:01 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleField.name
     *
     * @mbg.generated Tue Jan 17 14:36:01 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WxArticleField.id
     *
     * @return the value of WxArticleField.id
     *
     * @mbg.generated Tue Jan 17 14:36:01 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WxArticleField.id
     *
     * @param id the value for WxArticleField.id
     *
     * @mbg.generated Tue Jan 17 14:36:01 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WxArticleField.name
     *
     * @return the value of WxArticleField.name
     *
     * @mbg.generated Tue Jan 17 14:36:01 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WxArticleField.name
     *
     * @param name the value for WxArticleField.name
     *
     * @mbg.generated Tue Jan 17 14:36:01 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}