package com.zc.bean;

import java.util.Date;

public class WxArticleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.title
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.structure_type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String structureType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.article_url
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String articleUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.account_id
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.account_name
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.idx
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.summary
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.article_tags
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String articleTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.stat_type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private String statType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.read_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Integer readNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.like_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.reward_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Integer rewardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.comment_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Integer commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.like_rate
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Float likeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.score
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.speed
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Float speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.quality
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Float quality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.relative_score
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Float relativeScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.is_active
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WxArticleInfo.create_date
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    private Date createDate;

    /**
     
     * This method returns the value of the database column WxArticleInfo.title
     *
     * @return the value of WxArticleInfo.title
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.title
     *
     * @param title the value for WxArticleInfo.title
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.type
     *
     * @return the value of WxArticleInfo.type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.type
     *
     * @param type the value for WxArticleInfo.type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.structure_type
     *
     * @return the value of WxArticleInfo.structure_type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getStructureType() {
        return structureType;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.structure_type
     *
     * @param structureType the value for WxArticleInfo.structure_type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setStructureType(String structureType) {
        this.structureType = structureType == null ? null : structureType.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.article_url
     *
     * @return the value of WxArticleInfo.article_url
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getArticleUrl() {
        return articleUrl;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.article_url
     *
     * @param articleUrl the value for WxArticleInfo.article_url
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setArticleUrl(String articleUrl) {
        this.articleUrl = articleUrl == null ? null : articleUrl.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.account_id
     *
     * @return the value of WxArticleInfo.account_id
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.account_id
     *
     * @param accountId the value for WxArticleInfo.account_id
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.account_name
     *
     * @return the value of WxArticleInfo.account_name
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.account_name
     *
     * @param accountName the value for WxArticleInfo.account_name
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.idx
     *
     * @return the value of WxArticleInfo.idx
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.idx
     *
     * @param idx the value for WxArticleInfo.idx
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.summary
     *
     * @return the value of WxArticleInfo.summary
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.summary
     *
     * @param summary the value for WxArticleInfo.summary
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.article_tags
     *
     * @return the value of WxArticleInfo.article_tags
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getArticleTags() {
        return articleTags;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.article_tags
     *
     * @param articleTags the value for WxArticleInfo.article_tags
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setArticleTags(String articleTags) {
        this.articleTags = articleTags == null ? null : articleTags.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.stat_type
     *
     * @return the value of WxArticleInfo.stat_type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getStatType() {
        return statType;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.stat_type
     *
     * @param statType the value for WxArticleInfo.stat_type
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setStatType(String statType) {
        this.statType = statType == null ? null : statType.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.read_num
     *
     * @return the value of WxArticleInfo.read_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.read_num
     *
     * @param readNum the value for WxArticleInfo.read_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.like_num
     *
     * @return the value of WxArticleInfo.like_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.like_num
     *
     * @param likeNum the value for WxArticleInfo.like_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.reward_num
     *
     * @return the value of WxArticleInfo.reward_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Integer getRewardNum() {
        return rewardNum;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.reward_num
     *
     * @param rewardNum the value for WxArticleInfo.reward_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setRewardNum(Integer rewardNum) {
        this.rewardNum = rewardNum;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.comment_num
     *
     * @return the value of WxArticleInfo.comment_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.comment_num
     *
     * @param commentNum the value for WxArticleInfo.comment_num
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.like_rate
     *
     * @return the value of WxArticleInfo.like_rate
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Float getLikeRate() {
        return likeRate;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.like_rate
     *
     * @param likeRate the value for WxArticleInfo.like_rate
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setLikeRate(Float likeRate) {
        this.likeRate = likeRate;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.score
     *
     * @return the value of WxArticleInfo.score
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Float getScore() {
        return score;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.score
     *
     * @param score the value for WxArticleInfo.score
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.speed
     *
     * @return the value of WxArticleInfo.speed
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Float getSpeed() {
        return speed;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.speed
     *
     * @param speed the value for WxArticleInfo.speed
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.quality
     *
     * @return the value of WxArticleInfo.quality
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Float getQuality() {
        return quality;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.quality
     *
     * @param quality the value for WxArticleInfo.quality
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setQuality(Float quality) {
        this.quality = quality;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.relative_score
     *
     * @return the value of WxArticleInfo.relative_score
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Float getRelativeScore() {
        return relativeScore;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.relative_score
     *
     * @param relativeScore the value for WxArticleInfo.relative_score
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setRelativeScore(Float relativeScore) {
        this.relativeScore = relativeScore;
    }

    public String getKeywords() {
        return keywords;
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.is_active
     *
     * @return the value of WxArticleInfo.is_active
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * @param isActive the value for WxArticleInfo.is_active
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method returns the value of the database column WxArticleInfo.create_date
     *
     * @return the value of WxArticleInfo.create_date
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.create_date
     *
     * @param createDate the value for WxArticleInfo.create_date
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.keywords
     *
     * @param keywords the value for WxArticleInfo.keywords
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }


    /**
     
     * This method returns the value of the database column WxArticleInfo.publish_time
     *
     * @return the value of WxArticleInfo.publish_time
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     
     * This method sets the value of the database column WxArticleInfo.publish_time
     *
     * @param publishTime the value for WxArticleInfo.publish_time
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     
     * This method returns the value of the database column WxArticleInfo.stat_time
     *
     * @return the value of WxArticleInfo.stat_time
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public String getStatTime() {
        return statTime;
    }

    /**
     * This method sets the value of the database column WxArticleInfo.stat_time
     *
     * @param statTime the value for WxArticleInfo.stat_time
     *
     * @mbg.generated Tue Jan 17 16:43:58 CST 2017
     */
    public void setStatTime(String statTime) {
        this.statTime = statTime == null ? null : statTime.trim();
    }

    private String keywords;

    public String getTopicId() {
        return topicId;
    }

    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }

    public String getTopicTitle() {
        return topicTitle;
    }

    public void setTopicTitle(String topicTitle) {
        this.topicTitle = topicTitle;
    }

    private String statTime;

    private String publishTime;

    private String topicId;

    private String topicTitle;
}